"""Emit strategy_library_v2_batch1_audit.{md,csv} from code inspection (run from repo root)."""

from __future__ import annotations

import csv
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from src.features.feature_config import validate_no_registry_duplicates
from src.features.feature_key import feature_key_from_config
from src.strategies.loader import grid_size, load_strategy, load_strategy_config, load_testing_config
from src.strategies.metadata import get_strategy_metadata

BATCH1 = [
    "intraday_ma_crossover",
    "rsi_failure_swing",
    "bollinger_squeeze_breakout",
    "bollinger_band_fade_chop",
    "donchian_channel_breakout",
    "consecutive_bar_exhaustion",
]


def _check_strategy(name: str) -> dict[str, str]:
    row: dict[str, str] = {"strategy": name}
    st = load_strategy(name)
    row["registered"] = "yes"
    row["supports_fast"] = str(getattr(st, "supports_fast", False))
    row["performance_tier"] = str(getattr(st, "performance_tier", ""))
    try:
        get_strategy_metadata(name)
        row["metadata_ok"] = "yes"
    except Exception as e:
        row["metadata_ok"] = f"no:{e}"
    p = _ROOT / "src" / "strategies" / "parameters" / f"{name}.yaml"
    t = _ROOT / "src" / "strategies" / "testing_parameters" / f"{name}_focused.yaml"
    row["parameters_yaml"] = "yes" if p.is_file() else "no"
    row["focused_yaml"] = "yes" if t.is_file() else "no"
    row["validate_config"] = "yes" if callable(getattr(st, "validate_config", None)) else "no"
    req = list(st.required_features())
    row["required_features"] = " ".join(req)
    bad = [c for c in req if "LOOKAHEAD" in str(c)]
    row["lookahead_in_required"] = "yes" if bad else "no"
    row["context_key"] = "yes" if callable(getattr(st, "context_key", None)) else "no"
    row["normalized_param_key"] = "yes" if callable(getattr(st, "normalized_param_key", None)) else "no"
    row["gen_arrays_from_context"] = (
        "yes" if callable(getattr(st, "generate_signal_arrays_from_context", None)) else "no"
    )
    cfg = load_strategy_config(name)
    try:
        st.validate_config(cfg)
        row["default_params_validate"] = "yes"
    except Exception as e:
        row["default_params_validate"] = f"no:{e}"
    tcfg = load_testing_config(name)
    row["raw_grid_size"] = str(grid_size(tcfg))
    return row


def _feature_modules() -> str:
    lines = [
        "## Feature modules",
        "",
        "- `indicators.py`, `channels.py`, `regime.py`, `build_types.py`",
        "- `feature_key_from_config` includes `indicators`, `channels`, `regime` dataclass tuples.",
        "- `validate_no_registry_duplicates()`: called from `build_features` (no duplicate registry columns).",
        "- Channels: Donchian high/low use `shift(1).rolling(N)` — prior-exclusive (current bar excluded from level).",
        "- Indicators/channels/regime: no columns named with substring `LOOKAHEAD` in module outputs.",
        "",
    ]
    validate_no_registry_duplicates()
    lines.append("- Duplicate registry check: **pass**.")
    # import cycle smoke
    from src.features import feature_key as fk  # noqa: F401

    lines.append(f"- `feature_key` module import: OK ({fk.__file__}).")
    return "\n".join(lines)


def main() -> int:
    out_dir = _ROOT / "src" / "research" / "results"
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = [_check_strategy(s) for s in BATCH1]
    csv_path = out_dir / "strategy_library_v2_batch1_audit.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    md_path = out_dir / "strategy_library_v2_batch1_audit.md"
    lines = [
        "# Strategy Library v2 Batch 1 — implementation audit",
        "",
        "Auto-generated by `src/research/gen_batch1_audit.py`.",
        "",
        "## Strategies (six plugins)",
        "",
        "| check | all six |",
        "|-------|---------|",
    ]
    keys = [k for k in rows[0] if k != "strategy"]
    for k in keys:
        ok = all(r.get(k, "").startswith("yes") for r in rows)
        lines.append(f"| {k} | {'PASS' if ok else 'REVIEW'} |")
    lines.append("")
    lines.append("## Per-strategy CSV")
    lines.append("")
    lines.append(f"See `{csv_path.relative_to(_ROOT)}`.")
    lines.append("")
def main() -> int:
    out_dir = _ROOT / "src" / "research" / "results"
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = [_check_strategy(s) for s in BATCH1]
    csv_path = out_dir / "strategy_library_v2_batch1_audit.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    md_path = out_dir / "strategy_library_v2_batch1_audit.md"
    lines = [
        "# Strategy Library v2 Batch 1 — implementation audit",
        "",
        "Auto-generated by `src/research/gen_batch1_audit.py`.",
        "",
        "## Strategies (six plugins)",
        "",
        "| check | all six |",
        "|-------|---------|",
    ]
    keys = [k for k in rows[0] if k != "strategy"]
    for k in keys:
        ok = all(r.get(k, "").startswith("yes") for r in rows)
        lines.append(f"| {k} | {'PASS' if ok else 'REVIEW'} |")
    lines.append("")
    lines.append("## Per-strategy CSV")
    lines.append("")
    lines.append(f"See `{csv_path.relative_to(_ROOT)}`.")
    lines.append("")
    lines.append(_feature_modules())
    lines.append("")
    lines.append("## DataFrame fragmentation (Phase 2)")
    lines.append("")
    lines.append(
        "`channels.py`, `regime.py`, and `indicators.py` now append computed columns via a single "
        "`pd.concat` per module pass (dict of `Series` → `DataFrame`) to avoid pandas "
        "`PerformanceWarning: DataFrame is highly fragmented` from repeated `out[col] = ...` inserts. "
        "Formulas and column names are unchanged."
    )
    lines.append("")
    lines.append("## Feature build smoke (default Batch1 configs)")
    lines.append("")
    for s in BATCH1:
        st = load_strategy(s)
        cfg = load_strategy_config(s)
        req = st.required_features()
        fk = feature_key_from_config(cfg)
        lines.append(f"- **{s}**: required_features count={len(req)}, feature_key length={len(fk)}")
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {csv_path}", flush=True)
    print(f"Wrote {md_path}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
